/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateWatchArgs } from "./CreateWatchArgs";
import { UpdateWatchArgs } from "./UpdateWatchArgs";
import { DeleteWatchArgs } from "./DeleteWatchArgs";
import { WatchCountArgs } from "./WatchCountArgs";
import { WatchFindManyArgs } from "./WatchFindManyArgs";
import { WatchFindUniqueArgs } from "./WatchFindUniqueArgs";
import { Watch } from "./Watch";
import { WatchService } from "../watch.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Watch)
export class WatchResolverBase {
  constructor(
    protected readonly service: WatchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "read",
    possession: "any",
  })
  async _watchesMeta(
    @graphql.Args() args: WatchCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Watch])
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "read",
    possession: "any",
  })
  async watches(@graphql.Args() args: WatchFindManyArgs): Promise<Watch[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Watch, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "read",
    possession: "own",
  })
  async watch(
    @graphql.Args() args: WatchFindUniqueArgs
  ): Promise<Watch | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Watch)
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "create",
    possession: "any",
  })
  async createWatch(@graphql.Args() args: CreateWatchArgs): Promise<Watch> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Watch)
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "update",
    possession: "any",
  })
  async updateWatch(
    @graphql.Args() args: UpdateWatchArgs
  ): Promise<Watch | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Watch)
  @nestAccessControl.UseRoles({
    resource: "Watch",
    action: "delete",
    possession: "any",
  })
  async deleteWatch(
    @graphql.Args() args: DeleteWatchArgs
  ): Promise<Watch | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
